# File taken originally from https://github.com/aarron-lee/SimpleDeckyTDP/blob/main/.github/workflows/release.yml
# Copyright (c) 2023, Aarron Lee
# Original Copyright (c) 2022-2023, Steam Deck Homebrew
# Licensed under the BSD 3-Clause License.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup PNPM@10
        uses: pnpm/action-setup@v4
        with:
          version: "10.11.0"

      - name: Build frontend from source
        run: |
          pnpm i
          pnpm run build
        continue-on-error: true

      - name: Download Decky Plugin CLI
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky

      - name: Build plugin
        run: |
          $(pwd)/cli/decky plugin build $(pwd)
          unzip "out/DeckPass.zip" -d "out/DeckPass"

      - name: show files
        run: |
          ls out/DeckPass.zip
          7z l out/DeckPass.zip

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DeckPass
          path: out/DeckPass.zip

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - run: mkdir /tmp/artifacts

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/artifacts/DeckPass/DeckPass.zip
          tag_name: ${{ github.ref_name }}
          body: |
            DeckPass
          draft: true
          generate_release_notes: true
          prerelease: contains(github.ref, 'pre')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}